// Thin re-export facade — new code should import from '../worker-api' directly.
export {
  onKeyhiveStateChanged,
  getIdentity,
  getContactCard,
  receiveContactCard,
  getKnownContacts,
  getDocMembers,
  getMyAccess,
  rendezvousCreateShare,
  rendezvousReceive,
  rendezvousCreateDeviceLink,
  rendezvousJoinDeviceLink,
  rendezvousCancel,
  onRendezvousEvent,
  listDevices,
  removeDevice,
  changeDeviceRole,
  ensureUserGroup,
  linkDevice,
  getLinkPayload,
  addMember,
  revokeMember,
  changeRole,
} from '../worker-api';
export type { DeviceInfo, IdentityInfo, MemberInfo, LinkPayload } from '../worker-api';
